name=input("Enter your name: ")
gender=input('enter your gender')
age=int(input("Enter your age: "))
Fee=float(input("Enter your fee: "))
marks=int(input("Enter your marks: "))

print("Name: ",name)
print("Gender: ",gender)
print("Age: ",age)
print("Fee: ",Fee)
print("Marks: ",marks)
